Purpose

The purpose of this data science project is to come up with a pricing model for the the rents charged for german apartments. The project aims to build a predictive model for rents based on facilities and properties boasted by each individual listing. The model may be useful to companies or individuals looking to price their apartments for rents.

Imports

In [78]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
from pathlib import Path
import requests
import pandas_profiling
from pandas_profiling.utils.cache import cache_file

Data Wrangling Objectives

Fundamental questions to resolve in this notebook before moving on.
Is this the right type of data that should be used to model rent prices?
    Has the required target value been identified?
    Are there potentially useful features?
Are there fundamental issues with the data?

Loading the raw data

In [79]:
immo_data= pd.read_csv('../data/raw/immo_data.csv')

Data Definition

The features of an apartment (the entity) has to be defined in sufficient detail for further analysis. In doing so we gain an understanding of its relevance to the each apartment record. We also identify our feature of interest - the target feature - which in our case is the rent charged for each apartment, and start to get a sense for how these features are related to our target feature. Of relevance is representing the features in the right data format for further processing and taking note of features that have limited values.

We start inspecting the dataset by reviewing summary level information about the features and viewing the first view entries

This report gives us all the summary level information we want about the data set in a lot of detail

In [80]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [81]:
report = immo_data.profile_report(sort='None', html={'style':{'full_width': True}}, progress_bar=False)

The info command gives a sense to the shape and quality of the dataset.

In [82]:
immo_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 268850 entries, 0 to 268849
Data columns (total 49 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   regio1                    268850 non-null  object
 1   serviceCharge             261941 non-null  float64
 2   heatingType               223994 non-null  object
 3   telekomTvOffer            236231 non-null  object
 4   telekomHybridUploadSpeed  45020 non-null   float64
 5   newlyConst                268850 non-null  bool
 6   balcony                   268850 non-null  bool
 7   picturecount              268850 non-null  int64
 8   pricetrend                267018 non-null  float64
 9   telekomUploadSpeed        235492 non-null  float64
 10  totalRent                 228333 non-null  float64
 11  yearConstructed           211805 non-null  float64
 12  scoutId                   268850 non-null  int64
 13  noParkSpaces              93052 non-null   float64
 14  firingTypes               211886 non-null  object
 15  hasKitchen                268850 non-null  bool
 16  geo_bln                   268850 non-null  object
 17  cellar                    268850 non-null  bool
 18  yearConstructedRange      211805 non-null  float64
 19  baseRent                  268850 non-null  float64
 20  houseNumber               197832 non-null  object
 21  livingSpace               268850 non-null  float64
 22  geo_krs                   268850 non-null  object
 23  condition                 200361 non-null  object
 24  interiorQual              156185 non-null  object
 25  petsAllowed               154277 non-null  object
 26  street                    268850 non-null  object
 27  streetPlain               197837 non-null  object
 28  lift                      268850 non-null  bool
 29  baseRentRange             268850 non-null  int64
 30  typeOfFlat                232236 non-null  object
 31  geo_plz                   268850 non-null  int64
 32  noRooms                   268850 non-null  float64
 33  thermalChar               162344 non-null  float64
 34  floor                     217541 non-null  float64
 35  numberOfFloors            171118 non-null  float64
 36  noRoomsRange              268850 non-null  int64
 37  garden                    268850 non-null  bool
 38  livingSpaceRange          268850 non-null  int64
 39  regio2                    268850 non-null  object
 40  regio3                    268850 non-null  object
 41  description               249103 non-null  object
 42  facilities                215926 non-null  object
 43  heatingCosts              85518 non-null   float64
 44  energyEfficiencyClass     77787 non-null   object
 45  lastRefurbish             80711 non-null   float64
 46  electricityBasePrice      46846 non-null   float64
 47  electricityKwhPrice       46846 non-null   float64
 48  date                      268850 non-null  object
dtypes: bool(6), float64(18), int64(6), object(19)
memory usage: 89.7+ MB

We observe that the dataset has 49 features associated with 268,850 apartment records that have been put up for rent. The dataset features comprise of 4 main datatypes, including 6 boolean, 18 float, 6 integer and 19 object datatypes. We would need to verfiy that these datatypes are accurate in the context of our goal of developing a price model for rent. We also note a varying level of quality associated with each feature in terms of how many records exist for the particular feature. We would need to deal with those features that have a lot of empty values. One last observation is the amount of memory used up by the dataset (89.7+ MB).This size is manageable with the operating system currently in use. A larger dataset would necessitate the use of additional memory, possibly with cloud computing technologies.

In [83]:
immo_data.head()

,regio1,serviceCharge,heatingType,telekomTvOffer,telekomHybridUploadSpeed,newlyConst,balcony,picturecount,pricetrend,telekomUploadSpeed,totalRent,yearConstructed,scoutId,noParkSpaces,firingTypes,hasKitchen,geo_bln,cellar,yearConstructedRange,baseRent,houseNumber,livingSpace,geo_krs,condition,interiorQual,petsAllowed,street,streetPlain,lift,baseRentRange,typeOfFlat,geo_plz,noRooms,thermalChar,floor,numberOfFloors,noRoomsRange,garden,livingSpaceRange,regio2,regio3,description,facilities,heatingCosts,energyEfficiencyClass,lastRefurbish,electricityBasePrice,electricityKwhPrice,date
0,Nordrhein_Westfalen,245.00,central_heating,ONE_YEAR_FREE,NaN,False,False,6,4.62,10.0,840.0,1965.0,96107057,1.0,oil,False,Nordrhein_Westfalen,True,2.0,595.0,244,86.00,Dortmund,well_kept,normal,NaN,Sch&uuml;ruferstra&szlig;e,Schüruferstraße,False,4,ground_floor,44269,4.0,181.4,1.0,3.0,4,True,4,Dortmund,Schüren,Die ebenerdig zu erreichende Erdgeschosswohnun...,Die Wohnung ist mit Laminat ausgelegt. Das Bad...,NaN,NaN,NaN,NaN,NaN,May19
1,Rheinland_Pfalz,134.00,self_contained_central_heating,ONE_YEAR_FREE,NaN,False,True,8,3.47,10.0,NaN,1871.0,111378734,2.0,gas,False,Rheinland_Pfalz,False,1.0,800.0,NaN,89.00,Rhein_Pfalz_Kreis,refurbished,normal,no,no_information,NaN,False,5,ground_floor,67459,3.0,NaN,NaN,NaN,3,False,4,Rhein_Pfalz_Kreis,Böhl_Iggelheim,Alles neu macht der Mai – so kann es auch für ...,NaN,NaN,NaN,2019.0,NaN,NaN,May19
2,Sachsen,255.00,floor_heating,ONE_YEAR_FREE,10.0,True,True,8,2.72,2.4,1300.0,2019.0,113147523,1.0,NaN,False,Sachsen,True,9.0,965.0,4,83.80,Dresden,first_time_use,sophisticated,NaN,Turnerweg,Turnerweg,True,6,apartment,1097,3.0,NaN,3.0,4.0,3,False,4,Dresden,Äußere_Neustadt_Antonstadt,Der Neubau entsteht im Herzen der Dresdner Neu...,"* 9 m² Balkon\n* Bad mit bodengleicher Dusche,...",NaN,NaN,NaN,NaN,NaN,Oct19
3,Sachsen,58.15,district_heating,ONE_YEAR_FREE,NaN,False,True,9,1.53,40.0,NaN,1964.0,108890903,NaN,district_heating,False,Sachsen,False,2.0,343.0,35,58.15,Mittelsachsen_Kreis,NaN,NaN,NaN,Gl&uuml;ck-Auf-Stra&szlig;e,Glück-Auf-Straße,False,2,other,9599,3.0,86.0,3.0,NaN,3,False,2,Mittelsachsen_Kreis,Freiberg,Abseits von Lärm und Abgasen in Ihre neue Wohn...,NaN,87.23,NaN,NaN,NaN,NaN,May19
4,Bremen,138.00,self_contained_central_heating,NaN,NaN,False,True,19,2.46,NaN,903.0,1950.0,114751222,NaN,gas,False,Bremen,False,1.0,765.0,10,84.97,Bremen,refurbished,NaN,NaN,Hermann-Henrich-Meier-Allee,Hermann-Henrich-Meier-Allee,False,5,apartment,28213,3.0,188.9,1.0,NaN,3,False,4,Bremen,Neu_Schwachhausen,Es handelt sich hier um ein saniertes Mehrfami...,Diese Wohnung wurde neu saniert und ist wie fo...,NaN,NaN,NaN,NaN,NaN,Feb20

The head method allows us to see some, but not all the features of the dataset. We can change the viewing options with as follows.

In [85]:
pd.options.display.max_columns = None
display(immo_data)

,regio1,serviceCharge,heatingType,telekomTvOffer,telekomHybridUploadSpeed,newlyConst,balcony,picturecount,pricetrend,telekomUploadSpeed,totalRent,yearConstructed,scoutId,noParkSpaces,firingTypes,hasKitchen,geo_bln,cellar,yearConstructedRange,baseRent,houseNumber,livingSpace,geo_krs,condition,interiorQual,petsAllowed,street,streetPlain,lift,baseRentRange,typeOfFlat,geo_plz,noRooms,thermalChar,floor,numberOfFloors,noRoomsRange,garden,livingSpaceRange,regio2,regio3,description,facilities,heatingCosts,energyEfficiencyClass,lastRefurbish,electricityBasePrice,electricityKwhPrice,date
0,Nordrhein_Westfalen,245.00,central_heating,ONE_YEAR_FREE,NaN,False,False,6,4.62,10.0,840.0,1965.0,96107057,1.0,oil,False,Nordrhein_Westfalen,True,2.0,595.0,244,86.00,Dortmund,well_kept,normal,NaN,Sch&uuml;ruferstra&szlig;e,Schüruferstraße,False,4,ground_floor,44269,4.0,181.40,1.0,3.0,4,True,4,Dortmund,Schüren,Die ebenerdig zu erreichende Erdgeschosswohnun...,Die Wohnung ist mit Laminat ausgelegt. Das Bad...,NaN,NaN,NaN,NaN,NaN,May19
1,Rheinland_Pfalz,134.00,self_contained_central_heating,ONE_YEAR_FREE,NaN,False,True,8,3.47,10.0,NaN,1871.0,111378734,2.0,gas,False,Rheinland_Pfalz,False,1.0,800.0,NaN,89.00,Rhein_Pfalz_Kreis,refurbished,normal,no,no_information,NaN,False,5,ground_floor,67459,3.0,NaN,NaN,NaN,3,False,4,Rhein_Pfalz_Kreis,Böhl_Iggelheim,Alles neu macht der Mai – so kann es auch für ...,NaN,NaN,NaN,2019.0,NaN,NaN,May19
2,Sachsen,255.00,floor_heating,ONE_YEAR_FREE,10.0,True,True,8,2.72,2.4,1300.0,2019.0,113147523,1.0,NaN,False,Sachsen,True,9.0,965.0,4,83.80,Dresden,first_time_use,sophisticated,NaN,Turnerweg,Turnerweg,True,6,apartment,1097,3.0,NaN,3.0,4.0,3,False,4,Dresden,Äußere_Neustadt_Antonstadt,Der Neubau entsteht im Herzen der Dresdner Neu...,"* 9 m² Balkon\n* Bad mit bodengleicher Dusche,...",NaN,NaN,NaN,NaN,NaN,Oct19
3,Sachsen,58.15,district_heating,ONE_YEAR_FREE,NaN,False,True,9,1.53,40.0,NaN,1964.0,108890903,NaN,district_heating,False,Sachsen,False,2.0,343.0,35,58.15,Mittelsachsen_Kreis,NaN,NaN,NaN,Gl&uuml;ck-Auf-Stra&szlig;e,Glück-Auf-Straße,False,2,other,9599,3.0,86.00,3.0,NaN,3,False,2,Mittelsachsen_Kreis,Freiberg,Abseits von Lärm und Abgasen in Ihre neue Wohn...,NaN,87.23,NaN,NaN,NaN,NaN,May19
4,Bremen,138.00,self_contained_central_heating,NaN,NaN,False,True,19,2.46,NaN,903.0,1950.0,114751222,NaN,gas,False,Bremen,False,1.0,765.0,10,84.97,Bremen,refurbished,NaN,NaN,Hermann-Henrich-Meier-Allee,Hermann-Henrich-Meier-Allee,False,5,apartment,28213,3.0,188.90,1.0,NaN,3,False,4,Bremen,Neu_Schwachhausen,Es handelt sich hier um ein saniertes Mehrfami...,Diese Wohnung wurde neu saniert und ist wie fo...,NaN,NaN,NaN,NaN,NaN,Feb20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
268845,Bayern,90.00,heat_pump,ONE_YEAR_FREE,NaN,False,True,0,2.74,10.0,910.0,2016.0,115641081,1.0,geothermal,False,Bayern,True,9.0,820.0,NaN,90.00,Weilheim_Schongau_Kreis,mint_condition,sophisticated,no,no_information,NaN,False,6,roof_storey,82390,3.0,NaN,NaN,NaN,3,False,4,Weilheim_Schongau_Kreis,Eberfing,"Diese schöne, neuwertige Wohnung im Dachgescho...",Fliesen und Parkett. Sichtbarer Dachstuhl.,NaN,NaN,NaN,NaN,NaN,Feb20
268846,Hessen,220.00,gas_heating,NaN,NaN,False,True,12,6.49,NaN,1150.0,1983.0,96981497,1.0,gas,True,Hessen,False,4.0,930.0,NaN,115.00,Bergstraße_Kreis,well_kept,sophisticated,negotiable,no_information,NaN,False,6,apartment,68519,3.5,NaN,1.0,1.0,3,False,5,Bergstraße_Kreis,Viernheim,Hier wird eine Wohnung im 2 Familienhaus angeb...,"Parkett, Kamin, Badewanne&Dusche\nGroßer Balko...",NaN,NaN,2015.0,NaN,NaN,May19
268847,Hessen,220.00,central_heating,ONE_YEAR_FREE,NaN,False,True,21,2.90,40.0,930.0,1965.0,66924271,1.0,gas,False,Hessen,True,2.0,650.0,10,95.00,Limburg_Weilburg_Kreis,well_kept,NaN,negotiable,Emsbachstrasse,Emsbachstrasse,False,5,apartment,65552,4.0,160.77,1.0,2.0,4,True,4,Limburg_Weilburg_Kreis,Limburg_an_der_Lahn,gemütliche 4-Zimmer-Wohnung im Obergeschoss ei...,"Böden: Wohn-/Schlafbereich = Laminat, Küche + ...",NaN,NaN,2019.0,NaN,NaN,Feb20
268848,Nordrhein_Westfalen,175.00,heat_pump,NaN,NaN,True,True,16,4.39,NaN,1015.0,2019.0,110938302,1.0,gas,False,Nordrhein_Westfalen,True,9.0,840.0,58,70.00,Köln,first_time_use,sophisticated,no,Idastra&szlig;e,Idastraße,True,6,apartment,51069,2.0,24.70,NaN,5.0,2,False,3,Köln,Dellbrück,"Neubau Erstbezug, gehobener Standard, alle Ein...","Wände:\nMaler­vlies, weiß gestrichen alter­nat...",40.00,NO_INFORMATION,2019.0,NaN,NaN,May19
268849,Hessen,315.00,central_heating,NaN,NaN,False,True,9,5.00,NaN,NaN,1972.0,115524054,1.0,district_heating,True,Hessen,True,3.0,935.0,8,77.00,Frankfurt_am_Main,modernized,NaN,NaN,Robert-Di&szlig;mann-Str.,Robert-Dißmann-Str.,True,6,apartment,65936,3.0,NaN,NaN,13.0,3,False,3,Frankfurt_am_Main,Sossenheim,"Schöne, helle, gut geschnittene und teilmöblie...","Balkon, Keller, Fahrstuhl, Vollbad, Einbauküch...",NaN,NaN,NaN,NaN,NaN,Feb20

First of all we need to identify each record uniquely. It would be preferrable not to use address information captured in teh street and streetPlain feature since this involves using 2 features and the datatype of these features is object (text), which makes it difficult for processing. However, there is scoutID feature that may work. This feature must have unique values for all 268,849 apartment records.

In [87]:
immo_data["scoutId"].nunique()

268850

Perfect! Each scoutId value is distinct and exists for all 268,850 records.

Let's now move scoutId to the first column as a unique identifier for each record.

In [94]:
cols = list(immo_data) #Get a list of column names for the dataset
#Get the list index of scoutId using list index method, pop it from the list using the list pop method, and insert the value (scoutId) as the first list item using the list insert method
cols.insert(0,cols.pop(cols.index("scoutId")))
#Use the ix indexer to rearrange the dataframe based on the new list column names

AttributeError: 'DataFrame' object has no attribute 'ix'

In [93]:
cols

['scoutId',
 'regio1',
 'serviceCharge',
 'heatingType',
 'telekomTvOffer',
 'telekomHybridUploadSpeed',
 'newlyConst',
 'balcony',
 'picturecount',
 'pricetrend',
 'telekomUploadSpeed',
 'totalRent',
 'yearConstructed',
 'noParkSpaces',
 'firingTypes',
 'hasKitchen',
 'geo_bln',
 'cellar',
 'yearConstructedRange',
 'baseRent',
 'houseNumber',
 'livingSpace',
 'geo_krs',
 'condition',
 'interiorQual',
 'petsAllowed',
 'street',
 'streetPlain',
 'lift',
 'baseRentRange',
 'typeOfFlat',
 'geo_plz',
 'noRooms',
 'thermalChar',
 'floor',
 'numberOfFloors',
 'noRoomsRange',
 'garden',
 'livingSpaceRange',
 'regio2',
 'regio3',
 'description',
 'facilities',
 'heatingCosts',
 'energyEfficiencyClass',
 'lastRefurbish',
 'electricityBasePrice',
 'electricityKwhPrice',
 'date']

We observe a variety of prices, costs and factors that may be used to determine rent. These includes serviceCharge, priceTrend, totalRent, baseRent, baseRentRange, heatingCosts, electricityBasePrice, electricityKwhPrice.

In [30]:
immo_data.dtypes

regio1                       object
serviceCharge               float64
heatingType                  object
telekomTvOffer               object
telekomHybridUploadSpeed    float64
newlyConst                     bool
balcony                        bool
picturecount                  int64
pricetrend                  float64
telekomUploadSpeed          float64
totalRent                   float64
yearConstructed             float64
scoutId                       int64
noParkSpaces                float64
firingTypes                  object
hasKitchen                     bool
geo_bln                      object
cellar                         bool
yearConstructedRange        float64
baseRent                    float64
houseNumber                  object
livingSpace                 float64
geo_krs                      object
condition                    object
interiorQual                 object
petsAllowed                  object
street                       object
streetPlain                  object
lift                           bool
baseRentRange                 int64
typeOfFlat                   object
geo_plz                       int64
noRooms                     float64
thermalChar                 float64
floor                       float64
numberOfFloors              float64
noRoomsRange                  int64
garden                         bool
livingSpaceRange              int64
regio2                       object
regio3                       object
description                  object
facilities                   object
heatingCosts                float64
energyEfficiencyClass        object
lastRefurbish               float64
electricityBasePrice        float64
electricityKwhPrice         float64
date                         object
dtype: object

In [31]:
immo_data[['serviceCharge', 'pricetrend', 'totalRent', 'baseRent', 'heatingCosts', 'electricityBasePrice']]

,serviceCharge,pricetrend,totalRent,baseRent,heatingCosts,electricityBasePrice
0,245.00,4.62,840.0,595.0,NaN,NaN
1,134.00,3.47,NaN,800.0,NaN,NaN
2,255.00,2.72,1300.0,965.0,NaN,NaN
3,58.15,1.53,NaN,343.0,87.23,NaN
4,138.00,2.46,903.0,765.0,NaN,NaN
...,...,...,...,...,...,...
268845,90.00,2.74,910.0,820.0,NaN,NaN
268846,220.00,6.49,1150.0,930.0,NaN,NaN
268847,220.00,2.90,930.0,650.0,NaN,NaN
268848,175.00,4.39,1015.0,840.0,40.00,NaN
268849,315.00,5.00,NaN,935.0,NaN,NaN

In [32]:
immo_data.describe()

,serviceCharge,telekomHybridUploadSpeed,picturecount,pricetrend,telekomUploadSpeed,totalRent,yearConstructed,scoutId,noParkSpaces,yearConstructedRange,baseRent,livingSpace,baseRentRange,geo_plz,noRooms,thermalChar,floor,numberOfFloors,noRoomsRange,livingSpaceRange,heatingCosts,lastRefurbish,electricityBasePrice,electricityKwhPrice
count,261941.000000,45020.0,268850.000000,267018.000000,235492.000000,2.283330e+05,211805.000000,2.688500e+05,93052.000000,211805.000000,2.688500e+05,268850.000000,268850.000000,268850.000000,268850.000000,162344.000000,217541.000000,171118.000000,268850.000000,268850.000000,85518.000000,80711.000000,46846.000000,46846.000000
mean,151.206113,10.0,9.791958,3.389001,28.804928,9.013315e+02,1966.400590,1.069697e+08,1.327634,3.714544,6.941294e+02,74.355548,3.765256,37283.022235,2.641261,114.749533,2.122405,3.572319,2.571542,3.070790,76.990866,2013.904536,89.113612,0.199769
std,308.295790,0.0,6.408399,1.964874,16.337151,3.323833e+04,46.992207,1.250093e+07,8.361403,2.738134,1.953602e+04,254.759208,2.214357,27798.037296,2.633440,61.653663,3.634934,6.375496,0.937594,1.407127,147.716278,10.963125,5.395805,0.009667
min,0.000000,10.0,0.000000,-12.330000,1.000000,0.000000e+00,1000.000000,2.887174e+07,0.000000,1.000000,0.000000e+00,0.000000,1.000000,852.000000,1.000000,0.100000,-1.000000,0.000000,1.000000,1.000000,0.000000,1015.000000,71.430000,0.170500
25%,95.000000,10.0,6.000000,2.000000,10.000000,4.698000e+02,1950.000000,1.066910e+08,1.000000,1.000000,3.380000e+02,54.000000,2.000000,9128.000000,2.000000,79.000000,1.000000,2.000000,2.000000,2.000000,54.000000,2012.000000,90.760000,0.191500
50%,135.000000,10.0,9.000000,3.390000,40.000000,6.500000e+02,1973.000000,1.111584e+08,1.000000,3.000000,4.900000e+02,67.320000,3.000000,38667.000000,3.000000,107.000000,2.000000,3.000000,3.000000,3.000000,70.000000,2017.000000,90.760000,0.198500
75%,190.000000,10.0,13.000000,4.570000,40.000000,9.850000e+02,1996.000000,1.137688e+08,1.000000,5.000000,7.990000e+02,87.000000,5.000000,57072.000000,3.000000,140.300000,3.000000,4.000000,3.000000,4.000000,90.000000,2019.000000,90.760000,0.205500
max,146118.000000,10.0,121.000000,14.920000,100.000000,1.575154e+07,2090.000000,1.157117e+08,2241.000000,9.000000,9.999999e+06,111111.000000,9.000000,99998.000000,999.990000,1996.000000,999.000000,999.000000,5.000000,7.000000,12613.000000,2919.000000,90.760000,0.227600

In [33]:
immo_data.regio1.nunique()

16

In [34]:
immo_data.regio1.value_counts()

Nordrhein_Westfalen       62863
Sachsen                   58154
Bayern                    21609
Sachsen_Anhalt            20124
Hessen                    17845
Niedersachsen             16593
Baden_Württemberg         16091
Berlin                    10406
Thüringen                  8388
Rheinland_Pfalz            8368
Brandenburg                6954
Schleswig_Holstein         6668
Mecklenburg_Vorpommern     6634
Hamburg                    3759
Bremen                     2965
Saarland                   1429
Name: regio1, dtype: int64

In [35]:
immo_data.heatingType.head()

0                   central_heating
1    self_contained_central_heating
2                     floor_heating
3                  district_heating
4    self_contained_central_heating
Name: heatingType, dtype: object

In [36]:
immo_data.heatingType.nunique()

13

In [37]:
immo_data.heatingType.unique()

array(['central_heating', 'self_contained_central_heating',
       'floor_heating', 'district_heating', 'gas_heating', 'oil_heating',
       nan, 'wood_pellet_heating', 'electric_heating',
       'combined_heat_and_power_plant', 'heat_pump',
       'night_storage_heater', 'stove_heating', 'solar_heating'],
      dtype=object)

In [38]:
immo_data.heatingType.value_counts()

central_heating                   128977
district_heating                   24808
gas_heating                        19955
self_contained_central_heating     19087
floor_heating                      17697
oil_heating                         5042
heat_pump                           2737
combined_heat_and_power_plant       1978
night_storage_heater                1341
wood_pellet_heating                  961
electric_heating                     901
stove_heating                        344
solar_heating                        166
Name: heatingType, dtype: int64

In [39]:
immo_data.heatingType.describe()

count              223994
unique                 13
top       central_heating
freq               128977
Name: heatingType, dtype: object

In [40]:
immo_data['telekomTvOffer'].head()

0    ONE_YEAR_FREE
1    ONE_YEAR_FREE
2    ONE_YEAR_FREE
3    ONE_YEAR_FREE
4              NaN
Name: telekomTvOffer, dtype: object

In [41]:
immo_data.telekomTvOffer.nunique()

3

In [42]:
immo_data.telekomTvOffer.value_counts()

ONE_YEAR_FREE    227632
NONE               4957
ON_DEMAND          3642
Name: telekomTvOffer, dtype: int64

In [43]:
immo_data.telekomTvOffer.unique()

array(['ONE_YEAR_FREE', nan, 'NONE', 'ON_DEMAND'], dtype=object)

In [44]:
immo_data.heatingType.value_counts()

central_heating                   128977
district_heating                   24808
gas_heating                        19955
self_contained_central_heating     19087
floor_heating                      17697
oil_heating                         5042
heat_pump                           2737
combined_heat_and_power_plant       1978
night_storage_heater                1341
wood_pellet_heating                  961
electric_heating                     901
stove_heating                        344
solar_heating                        166
Name: heatingType, dtype: int64

In [45]:
immo_data.firingTypes.unique()

array(['oil', 'gas', nan, 'district_heating', 'gas:electricity',
       'electricity', 'pellet_heating', 'natural_gas_light',
       'combined_heat_and_power_fossil_fuels',
       'district_heating:local_heating', 'steam_district_heating',
       'natural_gas_heavy', 'gas:district_heating', 'solar_heating:gas',
       'environmental_thermal_energy', 'local_heating',
       'gas:natural_gas_light', 'geothermal',
       'combined_heat_and_power_regenerative_energy', 'heat_supply',
       'oil:electricity', 'solar_heating', 'geothermal:solar_heating',
       'district_heating:electricity', 'liquid_gas', 'wood',
       'hydro_energy', 'combined_heat_and_power_renewable_energy', 'coal',
       'gas:steam_district_heating', 'bio_energy',
       'gas:environmental_thermal_energy', 'wood_chips', 'gas:oil',
       'solar_heating:wood', 'geothermal:gas',
       'solar_heating:gas:electricity',
       'gas:natural_gas_light:heat_supply', 'pellet_heating:gas',
       'solar_heating:gas:bio_energy', 'oil:wood',
       'electricity:combined_heat_and_power_fossil_fuels',
       'gas:natural_gas_heavy', 'solar_heating:oil',
       'combined_heat_and_power_bio_energy', 'pellet_heating:wood',
       'district_heating:combined_heat_and_power_fossil_fuels',
       'electricity:natural_gas_heavy',
       'district_heating:electricity:local_heating',
       'electricity:natural_gas_light', 'geothermal:district_heating',
       'electricity:bio_energy', 'district_heating:coal',
       'oil:district_heating', 'solar_heating:electricity',
       'pellet_heating:electricity', 'solar_heating:natural_gas_light',
       'solar_heating:oil:wood', 'solar_heating:district_heating',
       'district_heating:combined_heat_and_power_renewable_energy',
       'district_heating:electricity:local_heating:combined_heat_and_power_fossil_fuels',
       'solar_heating:pellet_heating', 'district_heating:heat_supply',
       'electricity:local_heating', 'natural_gas_light:heat_supply',
       'solar_heating:natural_gas_light:environmental_thermal_energy',
       'oil:environmental_thermal_energy',
       'electricity:environmental_thermal_energy', 'gas:bio_energy',
       'oil:natural_gas_light', 'gas:local_heating', 'pellet_heating:oil',
       'natural_gas_light:natural_gas_heavy',
       'gas:combined_heat_and_power_fossil_fuels',
       'district_heating:bio_energy',
       'district_heating:local_heating:combined_heat_and_power_fossil_fuels',
       'solar_heating:gas:district_heating',
       'solar_heating:wood:environmental_thermal_energy', 'gas:wood',
       'solar_heating:gas:wood', 'wind_energy', 'geothermal:electricity',
       'district_heating:electricity:combined_heat_and_power_fossil_fuels',
       'gas:district_heating:local_heating', 'coal_coke',
       'natural_gas_light:liquid_gas', 'electricity:wood',
       'local_heating:combined_heat_and_power_fossil_fuels',
       'geothermal:bio_energy',
       'solar_heating:gas:electricity:coal:coal_coke:local_heating',
       'pellet_heating:district_heating', 'solar_heating:local_heating',
       'district_heating:combined_heat_and_power_regenerative_energy',
       'gas:electricity:environmental_thermal_energy',
       'liquid_gas:steam_district_heating:wood:wood_chips:coal_coke:local_heating:heat_supply:bio_energy:wind_energy:hydro_energy:environmental_thermal_energy:combined_heat_and_power_fossil_fuels',
       'natural_gas_light:wood',
       'district_heating:local_heating:combined_heat_and_power_renewable_energy',
       'pellet_heating:natural_gas_light', 'solar_heating:heat_supply',
       'geothermal:solar_heating:pellet_heating:gas', 'gas:heat_supply',
       'gas:oil:electricity',
       'district_heating:combined_heat_and_power_fossil_fuels:combined_heat_and_power_regenerative_energy',
       'pellet_heating:wood:wood_chips', 'solar_heating:liquid_gas',
       'geothermal:solar_heating:pellet_heating',
       'geothermal:combined_heat_and_power_fossil_fuels',
       'district_heating:natural_gas_heavy',
       'electricity:coal:natural_gas_light:natural_gas_heavy:liquid_gas:steam_district_heating:wood:wood_chips:coal_coke:local_heating:heat_supply:bio_energy:wind_energy',
       'district_heating:wood', 'solar_heating:gas:natural_gas_light',
       'district_heating:electricity:natural_gas_heavy',
       'natural_gas_heavy:local_heating', 'solar_heating:gas:oil:coal',
       'district_heating:wood:bio_energy',
       'solar_heating:environmental_thermal_energy',
       'geothermal:solar_heating:pellet_heating:district_heating',
       'solar_heating:wood_chips', 'district_heating:natural_gas_light',
       'gas:oil:district_heating',
       'solar_heating:pellet_heating:bio_energy', 'geothermal:wood',
       'gas:district_heating:electricity',
       'solar_heating:oil:electricity',
       'solar_heating:pellet_heating:gas', 'gas:liquid_gas',
       'gas:wood_chips',
       'gas:oil:district_heating:electricity:coal:natural_gas_light',
       'geothermal:solar_heating:gas', 'electricity:wood_chips',
       'electricity:coal', 'solar_heating:bio_energy',
       'district_heating:hydro_energy'], dtype=object)

There are a lot of firingTypes. Need to split the items to see which of these are unique

In [46]:
split_data = immo_data["firingTypes"].str.split(":", expand = True)

In [47]:
split_data.tail(50)

,0,1,2,3,4,5,6,7,8,9,10,11,12
268800,electricity,None,None,None,None,None,None,None,None,None,None,None,None
268801,gas,None,None,None,None,None,None,None,None,None,None,None,None
268802,gas,None,None,None,None,None,None,None,None,None,None,None,None
268803,gas,None,None,None,None,None,None,None,None,None,None,None,None
268804,gas,None,None,None,None,None,None,None,None,None,None,None,None
268805,natural_gas_light,None,None,None,None,None,None,None,None,None,None,None,None
268806,district_heating,None,None,None,None,None,None,None,None,None,None,None,None
268807,gas,None,None,None,None,None,None,None,None,None,None,None,None
268808,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
268809,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
268810,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
268811,natural_gas_light,None,None,None,None,None,None,None,None,None,None,None,None
268812,gas,None,None,None,None,None,None,None,None,None,None,None,None
268813,district_heating,None,None,None,None,None,None,None,None,None,None,None,None
268814,electricity,None,None,None,None,None,None,None,None,None,None,None,None
268815,district_heating,None,None,None,None,None,None,None,None,None,None,None,None
268816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
268817,natural_gas_heavy,None,None,None,None,None,None,None,None,None,None,None,None
268818,gas,None,None,None,None,None,None,None,None,None,None,None,None
268819,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
268820,gas,None,None,None,None,None,None,None,None,None,None,None,None
268821,gas,None,None,None,None,None,None,None,None,None,None,None,None
268822,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
268823,natural_gas_light,None,None,None,None,None,None,None,None,None,None,None,None
268824,district_heating,None,None,None,None,None,None,None,None,None,None,None,None
268825,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
268826,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
268827,pellet_heating,None,None,None,None,None,None,None,None,None,None,None,None
268828,oil,None,None,None,None,None,None,None,None,None,None,None,None
268829,district_heating,None,None,None,None,None,None,None,None,None,None,None,None
268830,natural_gas_heavy,None,None,None,None,None,None,None,None,None,None,None,None
268831,gas,None,None,None,None,None,None,None,None,None,None,None,None
268832,gas,None,None,None,None,None,None,None,None,None,None,None,None
268833,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
268834,gas,None,None,None,None,None,None,None,None,None,None,None,None
268835,gas,None,None,None,None,None,None,None,None,None,None,None,None
268836,gas,None,None,None,None,None,None,None,None,None,None,None,None
268837,natural_gas_light,None,None,None,None,None,None,None,None,None,None,None,None
268838,heat_supply,None,None,None,None,None,None,None,None,None,None,None,None
268839,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
268840,district_heating,None,None,None,None,None,None,None,None,None,None,None,None
268841,gas,electricity,None,None,None,None,None,None,None,None,None,None,None
268842,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
268843,gas,None,None,None,None,None,None,None,None,None,None,None,None
268844,gas,None,None,None,None,None,None,None,None,None,None,None,None
268845,geothermal,None,None,None,None,None,None,None,None,None,None,None,None
268846,gas,None,None,None,None,None,None,None,None,None,None,None,None
268847,gas,None,None,None,None,None,None,None,None,None,None,None,None
268848,gas,None,None,None,None,None,None,None,None,None,None,None,None
268849,district_heating,None,None,None,None,None,None,None,None,None,None,None,None

We have an entry with 13 possible firing types. But most entries have one. We'll give these firing types columns from 1 to 13

In [48]:
split_data.columns = ["fuelType1", "fuelType2", "fuelType3", "fuelType4", "fuelType5", "fuelType6", "fuelType7", "fuelType8", "fuelType9", "fuelType10", "fuelType11", "fuelType12", "fuelType13"]

In [49]:
fueltypes = [[x, split_data[x].count()] for x in ["fuelType1", "fuelType2", "fuelType3", "fuelType4", "fuelType5", "fuelType6", "fuelType7", "fuelType8", "fuelType9", "fuelType10", "fuelType11", "fuelType12", "fuelType13"]]

In [50]:
fueltypes

[['fuelType1', 211886],
 ['fuelType2', 3407],
 ['fuelType3', 69],
 ['fuelType4', 17],
 ['fuelType5', 4],
 ['fuelType6', 4],
 ['fuelType7', 2],
 ['fuelType8', 2],
 ['fuelType9', 2],
 ['fuelType10', 2],
 ['fuelType11', 2],
 ['fuelType12', 2],
 ['fuelType13', 1]]

There are more entries in fuelType 1 and 2 than the others. We select only these columns and add to the dataframe

In [51]:
primaryFuels = split_data[["fuelType1","fuelType2"]]

In [52]:
immo_data = pd.concat([immo_data, primaryFuels], axis = 1)

In [53]:
immo_data.shape

(268850, 51)

In [54]:
immo_data[["heatingType", "firingTypes", "fuelType1", "fuelType2"]].head()

,heatingType,firingTypes,fuelType1,fuelType2
0,central_heating,oil,oil,None
1,self_contained_central_heating,gas,gas,None
2,floor_heating,NaN,NaN,NaN
3,district_heating,district_heating,district_heating,None
4,self_contained_central_heating,gas,gas,None

We can drop the firingTypes column since we have captured relevant information in

In [55]:
del immo_data["firingTypes"]

In [56]:
immo_data.shape

(268850, 50)

In [57]:
immo_data.fuelType1.unique()

array(['oil', 'gas', nan, 'district_heating', 'electricity',
       'pellet_heating', 'natural_gas_light',
       'combined_heat_and_power_fossil_fuels', 'steam_district_heating',
       'natural_gas_heavy', 'solar_heating',
       'environmental_thermal_energy', 'local_heating', 'geothermal',
       'combined_heat_and_power_regenerative_energy', 'heat_supply',
       'liquid_gas', 'wood', 'hydro_energy',
       'combined_heat_and_power_renewable_energy', 'coal', 'bio_energy',
       'wood_chips', 'combined_heat_and_power_bio_energy', 'wind_energy',
       'coal_coke'], dtype=object)

In [58]:
immo_data.fuelType1.nunique()

25

In [59]:
immo_data.fuelType2.nunique()

22

In [60]:
immo_data.fuelType1.describe()

count     211886
unique        25
top          gas
freq      112712
Name: fuelType1, dtype: object

In [61]:
immo_data.geo_bln.head()

0    Nordrhein_Westfalen
1        Rheinland_Pfalz
2                Sachsen
3                Sachsen
4                 Bremen
Name: geo_bln, dtype: object

In [62]:
immo_data[["regio1", "geo_bln"]].tail(50)

                        regio1                 geo_bln
268800                  Hessen                  Hessen
268801  Mecklenburg_Vorpommern  Mecklenburg_Vorpommern
268802             Brandenburg             Brandenburg
268803     Nordrhein_Westfalen     Nordrhein_Westfalen
268804     Nordrhein_Westfalen     Nordrhein_Westfalen
268805     Nordrhein_Westfalen     Nordrhein_Westfalen
268806       Baden_Württemberg       Baden_Württemberg
268807                 Sachsen                 Sachsen
268808                Saarland                Saarland
268809     Nordrhein_Westfalen     Nordrhein_Westfalen
268810             Brandenburg             Brandenburg
268811                  Bremen                  Bremen
268812     Nordrhein_Westfalen     Nordrhein_Westfalen
268813     Nordrhein_Westfalen     Nordrhein_Westfalen
268814       Baden_Württemberg       Baden_Württemberg
268815          Sachsen_Anhalt          Sachsen_Anhalt
268816       Baden_Württemberg       Baden_Württemberg
268817                  Hessen                  Hessen
268818                  Bayern                  Bayern
268819                  Hessen                  Hessen
268820          Sachsen_Anhalt          Sachsen_Anhalt
268821         Rheinland_Pfalz         Rheinland_Pfalz
268822          Sachsen_Anhalt          Sachsen_Anhalt
268823     Nordrhein_Westfalen     Nordrhein_Westfalen
268824           Niedersachsen           Niedersachsen
268825                 Sachsen                 Sachsen
268826                 Sachsen                 Sachsen
268827           Niedersachsen           Niedersachsen
268828     Nordrhein_Westfalen     Nordrhein_Westfalen
268829                  Berlin                  Berlin
268830     Nordrhein_Westfalen     Nordrhein_Westfalen
268831          Sachsen_Anhalt          Sachsen_Anhalt
268832                 Sachsen                 Sachsen
268833                 Sachsen                 Sachsen
268834                 Sachsen                 Sachsen
268835                  Bremen                  Bremen
268836          Sachsen_Anhalt          Sachsen_Anhalt
268837     Nordrhein_Westfalen     Nordrhein_Westfalen
268838          Sachsen_Anhalt          Sachsen_Anhalt
268839                  Bayern                  Bayern
268840                  Hessen                  Hessen
268841          Sachsen_Anhalt          Sachsen_Anhalt
268842                 Sachsen                 Sachsen
268843                 Sachsen                 Sachsen
268844     Nordrhein_Westfalen     Nordrhein_Westfalen
268845                  Bayern                  Bayern
268846                  Hessen                  Hessen
268847                  Hessen                  Hessen
268848     Nordrhein_Westfalen     Nordrhein_Westfalen
268849                  Hessen                  Hessen

In [63]:
immo_data['geo_bln'].unique()

array(['Nordrhein_Westfalen', 'Rheinland_Pfalz', 'Sachsen', 'Bremen',
       'Schleswig_Holstein', 'Baden_Württemberg', 'Thüringen', 'Hessen',
       'Niedersachsen', 'Bayern', 'Hamburg', 'Sachsen_Anhalt',
       'Mecklenburg_Vorpommern', 'Berlin', 'Brandenburg', 'Saarland'],
      dtype=object)

regio1 and geo_bln appear to have the same values. We can therefore go ahead and drop the column

In [64]:
del immo_data['geo_bln']

In [65]:
immo_data.shape

(268850, 49)

In [66]:
immo_data.houseNumber

0         244
1         NaN
2           4
3          35
4          10
         ...
268845    NaN
268846    NaN
268847     10
268848     58
268849      8
Name: houseNumber, Length: 268850, dtype: object

In [67]:
immo_data.geo_krs

0                        Dortmund
1               Rhein_Pfalz_Kreis
2                         Dresden
3             Mittelsachsen_Kreis
4                          Bremen
                   ...
268845    Weilheim_Schongau_Kreis
268846           Bergstraße_Kreis
268847     Limburg_Weilburg_Kreis
268848                       Köln
268849          Frankfurt_am_Main
Name: geo_krs, Length: 268850, dtype: object

In [68]:
immo_data.geo_krs.nunique()

419

In [69]:
immo_data.geo_krs.unique()

array(['Dortmund', 'Rhein_Pfalz_Kreis', 'Dresden', 'Mittelsachsen_Kreis',
       'Bremen', 'Schleswig_Flensburg_Kreis', 'Emmendingen_Kreis',
       'Gelsenkirchen', 'Chemnitz', 'Südliche_Weinstraße_Kreis', 'Hamm',
       'Weimar', 'Main_Kinzig_Kreis', 'Duisburg', 'Göttingen_Kreis',
       'Neumünster', 'Stuttgart', 'Leipzig', 'München', 'Hamburg',
       'Braunschweig', 'Esslingen_Kreis', 'Magdeburg', 'Schwerin',
       'Passau', 'Mettmann_Kreis', 'Vogtlandkreis', 'Groß_Gerau_Kreis',
       'Sächsische_Schweiz_Osterzgebirge_Kreis', 'Görlitz_Kreis',
       'Rheinisch_Bergischer_Kreis', 'Essen', 'Meißen_Kreis', 'Mannheim',
       'Wesermarsch_Kreis', 'Hochsauerlandkreis', 'Unna_Kreis',
       'Bautzen_Kreis', 'Berlin', 'Frankfurt_am_Main', 'Halle_Saale',
       'Steinburg_Kreis', 'Aschaffenburg', 'Oder_Spree_Kreis',
       'Bremerhaven', 'Zwickau_Kreis', 'Nordsachsen_Kreis',
       'Mansfeld_Südharz_Kreis', 'Alzey_Worms_Kreis', 'Gießen_Kreis',
       'Main_Taunus_Kreis', 'Zwickau', 'Wuppertal', 'Viersen_Kreis',
       'Düsseldorf', 'Gera', 'Böblingen_Kreis', 'Würzburg',
       'Kitzingen_Kreis', 'Stendal_Kreis', 'Nordvorpommern_Kreis',
       'Rhein_Erft_Kreis', 'Mülheim_an_der_Ruhr', 'Heilbronn',
       'Hersfeld_Rotenburg_Kreis', 'Aachen_Kreis', 'Erzgebirgskreis',
       'Baden_Baden', 'Tuttlingen_Kreis', 'Nürnberg', 'Heinsberg_Kreis',
       'Remscheid', 'Märkisch_Oderland_Kreis', 'Wiesbaden',
       'Wetteraukreis', 'Kassel', 'Bielefeld', 'Salzlandkreis', 'Aachen',
       'Harburg_Kreis', 'Höxter_Kreis', 'Germersheim_Kreis',
       'Brandenburg_an_der_Havel', 'Leipzig_Kreis', 'Aurich_Kreis',
       'Herzogtum_Lauenburg_Kreis', 'Karlsruhe', 'Frankenthal_Pfalz',
       'Rheingau_Taunus_Kreis', 'Nordwestmecklenburg_Kreis',
       'Ostvorpommern_Kreis', 'Emden', 'Rems_Murr_Kreis',
       'Altmarkkreis_Salzwedel', 'Straubing', 'Peine_Kreis',
       'Paderborn_Kreis', 'Düren_Kreis', 'Fürstenfeldbruck_Kreis', 'Kiel',
       'Unstrut_Hainich_Kreis', 'Ludwigslust_Kreis', 'Flensburg',
       'Borken_Kreis', 'Krefeld', 'Lörrach_Kreis', 'Saalekreis',
       'Wesel_Kreis', 'Recklinghausen_Kreis', 'Hagen',
       'Grafschaft_Bentheim_Kreis', 'Goslar_Kreis', 'Bergstraße_Kreis',
       'Börde_Kreis', 'Potsdam', 'Kusel_Kreis', 'Burgenlandkreis',
       'Holzminden_Kreis', 'Bad_Doberan_Kreis', 'Biberach_Kreis',
       'Coburg', 'Köln', 'Aschaffenburg_Kreis', 'Görlitz',
       'Dessau_Roßlau', 'Harz_Kreis', 'Ludwigsburg_Kreis', 'Herne',
       'Bad_Dürkheim_Kreis', 'Wittenberg_Kreis', 'Fürth',
       'Eichstätt_Kreis', 'Bochum', 'Pfaffenhofen_an_der_Ilm_Kreis',
       'Märkischer_Kreis', 'Trier', 'Rhein_Sieg_Kreis', 'Hannover',
       'Limburg_Weilburg_Kreis', 'Mönchengladbach', 'Bonn',
       'Anhalt_Bitterfeld_Kreis', 'Herford_Kreis', 'Neuss_Rhein_Kreis',
       'Plauen', 'Soest_Kreis', 'Erding_Kreis', 'Dahme_Spreewald_Kreis',
       'Mainz', 'Kleve_Kreis', 'Reutlingen_Kreis', 'Offenbach_Kreis',
       'Segeberg_Kreis', 'Emsland_Kreis', 'Hochtaunuskreis',
       'Schwarzwald_Baar_Kreis', 'Oberbergischer_Kreis',
       'Wunsiedel_im_Fichtelgebirge_Kreis', 'Hildburghausen_Kreis',
       'Wismar', 'Heilbronn_Kreis', 'Hannover_Kreis', 'Pirmasens',
       'Schmalkalden_Meiningen_Kreis', 'Ostalbkreis',
       'Oldenburg_Oldenburg', 'Mayen_Koblenz_Kreis', 'Ennepe_Ruhr_Kreis',
       'Uckermark_Kreis', 'Mainz_Bingen_Kreis', 'Erfurt',
       'Helmstedt_Kreis', 'Pinneberg_Kreis', 'Gütersloh_Kreis',
       'Starnberg_Kreis', 'Siegen_Wittgenstein_Kreis', 'Fulda_Kreis',
       'Würzburg_Kreis', 'Oberspreewald_Lausitz_Kreis', 'Göppingen_Kreis',
       'Werra_Meißner_Kreis', 'Lüneburg_Kreis', 'Wilhelmshaven',
       'Wolfsburg', 'Northeim_Kreis', 'Rhein_Lahn_Kreis',
       'Karlsruhe_Kreis', 'Freising_Kreis', 'Lübeck',
       'Minden_Lübbecke_Kreis', 'Rastatt_Kreis', 'Unterallgäu_Kreis',
       'Eisenach', 'Spree_Neiße_Kreis', 'Bad_Tölz_Wolfratshausen_Kreis',
       'Rendsburg_Eckernförde_Kreis', 'Augsburg',
       'Neustadt_a.d._Aisch_Bad_Windsheim_Kreis', 'Oberhavel_Kreis',
       'Schwalm_Eder_Kreis', 'Stralsund', 'Prignitz_Kreis', 'Hoyerswerda',
       'Straubing_Bogen_Kreis', 'Darmstadt_Dieburg_Kreis', 'Landshut',
       'Cochem_Zell_Kreis', 'Bad_Kreuznach_Kreis', 'Solingen',
       'Heidelberg', 'Hof', 'Neubrandenburg', 'Osnabrück_Kreis',
       'Landshut_Kreis', 'Donau_Ries_Kreis', 'Güstrow_Kreis',
       'Plön_Kreis', 'Koblenz', 'Alb_Donau_Kreis', 'Heidenheim_Kreis',
       'Bodenseekreis', 'Teltow_Fläming_Kreis', 'Westerwaldkreis',
       'Celle_Kreis', 'Potsdam_Mittelmark_Kreis', 'Hildesheim_Kreis',
       'Verden_Kreis', 'Rhein_Neckar_Kreis', 'Havelland_Kreis',
       'Dachau_Kreis', 'Rotenburg_Wümme_Kreis', 'Ostholstein_Kreis',
       'Pforzheim', 'Suhl', 'Stormarn_Kreis', 'Eichsfeld_Kreis',
       'Darmstadt', 'Regensburg', 'Nordhausen_Kreis', 'Sonneberg_Kreis',
       'Cottbus', 'Forchheim_Kreis', 'Erlangen', 'Nienburg_Weser_Kreis',
       'Waldeck_Frankenberg_Kreis', 'Dithmarschen_Kreis',
       'Diepholz_Kreis', 'Augsburg_Kreis', 'Deggendorf_Kreis',
       'Oberhausen', 'Neustadt_an_der_Weinstraße', 'Münster',
       'Osterode_am_Harz_Kreis', 'Freudenstadt_Kreis',
       'Marburg_Biedenkopf_Kreis', 'Stade_Kreis', 'Birkenfeld_Kreis',
       'Cuxhaven_Kreis', 'Rottal_Inn_Kreis', 'Rügen_Kreis',
       'München_Kreis', 'Osnabrück', 'Gotha_Kreis', 'Offenbach_am_Main',
       'Stadtverband_Saarbrücken_Kreis', 'Hof_Kreis', 'Kyffhäuserkreis',
       'Freiburg_im_Breisgau', 'Ravensburg_Kreis', 'Hameln_Pyrmont_Kreis',
       'Saalfeld_Rudolstadt_Kreis', 'Rostock', 'Saarlouis_Kreis',
       'Parchim_Kreis', 'Schwäbisch_Hall_Kreis', 'Bamberg_Kreis',
       'Weilheim_Schongau_Kreis', 'Lippe_Kreis', 'Müritz_Kreis',
       'Steinfurt_Kreis', 'Traunstein_Kreis', 'Ebersberg_Kreis',
       'Neuwied_Kreis', 'Kelheim_Kreis', 'Weimarer_Land_Kreis',
       'Saarpfalz_Kreis', 'Vechta_Kreis', 'Bitburg_Prüm_Kreis',
       'Ahrweiler_Kreis', 'Greifswald', 'Calw_Kreis', 'Gifhorn_Kreis',
       'Uelzen_Kreis', 'Altenburger_Land_Kreis', 'Ilm_Kreis',
       'Trier_Saarburg_Kreis', 'Lahn_Dill_Kreis', 'Worms',
       'Berchtesgadener_Land_Kreis', 'Breisgau_Hochschwarzwald_Kreis',
       'Oldenburg_Kreis', 'Barnim_Kreis', 'Erlangen_Höchstadt_Kreis',
       'Main_Spessart_Kreis', 'Rosenheim_Kreis', 'Bottrop',
       'Ludwigshafen_am_Rhein', 'Elbe_Elster_Kreis', 'Warendorf_Kreis',
       'Kassel_Kreis', 'Mecklenburg_Strelitz_Kreis',
       'Jerichower_Land_Kreis', 'Lüchow_Dannenberg_Kreis', 'Greiz_Kreis',
       'Euskirchen_Kreis', 'Regensburg_Kreis', 'Kaiserslautern_Kreis',
       'Salzgitter', 'Weißenburg_Gunzenhausen_Kreis', 'Ulm',
       'Altötting_Kreis', 'Landsberg_am_Lech_Kreis', 'Günzburg_Kreis',
       'Amberg_Sulzbach_Kreis', 'Wartburgkreis', 'Neu_Ulm_Kreis',
       'Lichtenfels_Kreis', 'Friesland_Kreis', 'Tübingen_Kreis',
       'Zollernalbkreis', 'Enzkreis', 'Miltenberg_Kreis',
       'Kaiserslautern', 'Schaumburg_Kreis', 'Waldshut_Kreis',
       'Delmenhorst', 'Bayreuth', 'Jena', 'Sömmerda_Kreis',
       'Nordfriesland_Kreis', 'Leer_Kreis',
       'Dillingen_an_der_Donau_Kreis', 'Nürnberger_Land_Kreis',
       'Ostprignitz_Ruppin_Kreis', 'Ingolstadt', 'Bad_Kissingen_Kreis',
       'Saale_Holzland_Kreis', 'Kaufbeuren', 'Speyer', 'Ansbach_Kreis',
       'Ammerland_Kreis', 'Rottweil_Kreis', 'Mühldorf_am_Inn_Kreis',
       'Weiden_in_der_Oberpfalz', 'Frankfurt_Oder',
       'Garmisch_Partenkirchen_Kreis', 'Main_Tauber_Kreis',
       'Ostallgäu_Kreis', 'Leverkusen', 'Rosenheim', 'Coburg_Kreis',
       'Neumarkt_in_der_Oberpfalz_Kreis', 'Aichach_Friedberg_Kreis',
       'Neunkirchen_Kreis', 'Coesfeld_Kreis', 'Lindau_Bodensee_Kreis',
       'Ortenaukreis', 'Rhein_Hunsrück_Kreis', 'Osterholz_Kreis',
       'Merzig_Wadern_Kreis', 'Heidekreis', 'Wolfenbüttel_Kreis',
       'Dingolfing_Landau_Kreis', 'Südwestpfalz_Kreis',
       'Bernkastel_Wittlich_Kreis', 'Bayreuth_Kreis', 'Schweinfurt_Kreis',
       'Demmin_Kreis', 'Passau_Kreis', 'Miesbach_Kreis', 'Ansbach',
       'Konstanz_Kreis', 'Fürth_Kreis', 'Tirschenreuth_Kreis',
       'Neckar_Odenwald_Kreis', 'Altenkirchen_Westerwald_Kreis',
       'Soltau_Fallingbostel_Kreis', 'Landau_in_der_Pfalz',
       'Uecker_Randow_Kreis', 'Zweibrücken',
       'Neuburg_Schrobenhausen_Kreis', 'Amberg', 'Donnersbergkreis',
       'Cloppenburg_Kreis', 'Hohenlohekreis', 'Roth_Kreis', 'Bamberg',
       'Schweinfurt', 'Vulkaneifel_Kreis', 'Vogelsbergkreis',
       'Schwandorf_Kreis', 'Cham_Kreis', 'Sigmaringen_Kreis',
       'Oberallgäu_Kreis', 'Regen_Kreis', 'Memmingen', 'Kempten_Allgäu',
       'Freyung_Grafenau_Kreis', 'Odenwaldkreis', 'Olpe_Kreis',
       'Saale_Orla_Kreis', 'Sankt_Wendel_Kreis', 'Kulmbach_Kreis',
       'Schwabach', 'Wittmund_Kreis', 'Haßberge_Kreis',
       'Rhön_Grabfeld_Kreis', 'Kronach_Kreis',
       'Neustadt_a.d._Waldnaab_Kreis'], dtype=object)

In [70]:
immo_data.select_dtypes('object')

,regio1,heatingType,telekomTvOffer,houseNumber,geo_krs,condition,interiorQual,petsAllowed,street,streetPlain,typeOfFlat,regio2,regio3,description,facilities,energyEfficiencyClass,date,fuelType1,fuelType2
0,Nordrhein_Westfalen,central_heating,ONE_YEAR_FREE,244,Dortmund,well_kept,normal,NaN,Sch&uuml;ruferstra&szlig;e,Schüruferstraße,ground_floor,Dortmund,Schüren,Die ebenerdig zu erreichende Erdgeschosswohnun...,Die Wohnung ist mit Laminat ausgelegt. Das Bad...,NaN,May19,oil,None
1,Rheinland_Pfalz,self_contained_central_heating,ONE_YEAR_FREE,NaN,Rhein_Pfalz_Kreis,refurbished,normal,no,no_information,NaN,ground_floor,Rhein_Pfalz_Kreis,Böhl_Iggelheim,Alles neu macht der Mai – so kann es auch für ...,NaN,NaN,May19,gas,None
2,Sachsen,floor_heating,ONE_YEAR_FREE,4,Dresden,first_time_use,sophisticated,NaN,Turnerweg,Turnerweg,apartment,Dresden,Äußere_Neustadt_Antonstadt,Der Neubau entsteht im Herzen der Dresdner Neu...,"* 9 m² Balkon\n* Bad mit bodengleicher Dusche,...",NaN,Oct19,NaN,NaN
3,Sachsen,district_heating,ONE_YEAR_FREE,35,Mittelsachsen_Kreis,NaN,NaN,NaN,Gl&uuml;ck-Auf-Stra&szlig;e,Glück-Auf-Straße,other,Mittelsachsen_Kreis,Freiberg,Abseits von Lärm und Abgasen in Ihre neue Wohn...,NaN,NaN,May19,district_heating,None
4,Bremen,self_contained_central_heating,NaN,10,Bremen,refurbished,NaN,NaN,Hermann-Henrich-Meier-Allee,Hermann-Henrich-Meier-Allee,apartment,Bremen,Neu_Schwachhausen,Es handelt sich hier um ein saniertes Mehrfami...,Diese Wohnung wurde neu saniert und ist wie fo...,NaN,Feb20,gas,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
268845,Bayern,heat_pump,ONE_YEAR_FREE,NaN,Weilheim_Schongau_Kreis,mint_condition,sophisticated,no,no_information,NaN,roof_storey,Weilheim_Schongau_Kreis,Eberfing,"Diese schöne, neuwertige Wohnung im Dachgescho...",Fliesen und Parkett. Sichtbarer Dachstuhl.,NaN,Feb20,geothermal,None
268846,Hessen,gas_heating,NaN,NaN,Bergstraße_Kreis,well_kept,sophisticated,negotiable,no_information,NaN,apartment,Bergstraße_Kreis,Viernheim,Hier wird eine Wohnung im 2 Familienhaus angeb...,"Parkett, Kamin, Badewanne&Dusche\nGroßer Balko...",NaN,May19,gas,None
268847,Hessen,central_heating,ONE_YEAR_FREE,10,Limburg_Weilburg_Kreis,well_kept,NaN,negotiable,Emsbachstrasse,Emsbachstrasse,apartment,Limburg_Weilburg_Kreis,Limburg_an_der_Lahn,gemütliche 4-Zimmer-Wohnung im Obergeschoss ei...,"Böden: Wohn-/Schlafbereich = Laminat, Küche + ...",NaN,Feb20,gas,None
268848,Nordrhein_Westfalen,heat_pump,NaN,58,Köln,first_time_use,sophisticated,no,Idastra&szlig;e,Idastraße,apartment,Köln,Dellbrück,"Neubau Erstbezug, gehobener Standard, alle Ein...","Wände:\nMaler­vlies, weiß gestrichen alter­nat...",NO_INFORMATION,May19,gas,None
268849,Hessen,central_heating,NaN,8,Frankfurt_am_Main,modernized,NaN,NaN,Robert-Di&szlig;mann-Str.,Robert-Dißmann-Str.,apartment,Frankfurt_am_Main,Sossenheim,"Schöne, helle, gut geschnittene und teilmöblie...","Balkon, Keller, Fahrstuhl, Vollbad, Einbauküch...",NaN,Feb20,district_heating,None